app:
    resource: '@AppBundle/Controller/'
    type: annotation

app_post:
    resource: '@AppBundle/Resources/config/routing.yml'
    prefix:   /post

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

