<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKr3tv0n\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKr3tv0n/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerKr3tv0n.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerKr3tv0n\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerKr3tv0n\appProdProjectContainer();
